### ISSUE TITLE
Additional link - Applications of Deep Learning

### ISSUE THREAD

**Issue by renatoviolin** [sayakpaul/TF-2.0-Hacks#3]
Hi,
thanks for sharing those resources about TF 2. 

I'd like to share the Applications of Deep Learning. This is a semester complete course by Jeff Heaton in video and notebooks. Very well organized and get updates all semester.

https://github.com/jeffheaton/t81_558_deep_learning

**Comment by sayakpaul** [comment]
Thanks for mentioining. I will add this.
